### ISSUE TITLE
Error when using sample input

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/MergeArabicNames#2]
Using the current main branch HEAD (commit [5444d7f](https://github.com/oduwsdl/MergeArabicNames/commit/5444d7ffe3381c1d2f0748eb1d87bad9973b4bd5))

```py
% python3 merge_names.py in/input.txt ./out.txt
Output file does not exist. One will be created under the name (output.json)
Traceback (most recent call last):
  File "/private/tmp/MergeArabicNames/merge_names.py", line 75, in <module>
    translated_names_dict = translate_names(names)
  File "/private/tmp/MergeArabicNames/merge_names.py", line 15, in translate_names
    transliterations = translator.translate(input_list, src='en', dest='ar')
  File "/private/tmp/MergeArabicNames/ss/lib/python3.10/site-packages/googletrans/client.py", line 177, in translate
    translated = self.translate(item, dest=dest, src=src, **kwargs)
  File "/private/tmp/MergeArabicNames/ss/lib/python3.10/site-packages/googletrans/client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "/private/tmp/MergeArabicNames/ss/lib/python3.10/site-packages/googletrans/client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "/private/tmp/MergeArabicNames/ss/lib/python3.10/site-packages/googletrans/gtoken.py", line 194, in do
    self._update()
  File "/private/tmp/MergeArabicNames/ss/lib/python3.10/site-packages/googletrans/gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
``

Python 3.10.0, macOS 12.1

**Comment by HussamHallak** [comment]
Please try to uninstall googletrans and install the lastest release:
pip uninstall googletrans
pip install googletrans==3.1.0a0

More about this issue here: 
[https://ws-dl.blogspot.com/2022/01/2021-01-03-googletrans-python-library.html ](https://ws-dl.blogspot.com/2022/01/2021-01-03-googletrans-python-library.html )

**Comment by machawk1** [comment]
@HussamHallak That worked. I have submitted PR https://github.com/oduwsdl/MergeArabicNames/pull/5 to ensure the alpha version is installed.
